Algoritmo "Aula2_atividade1"
//1) Elabore um algoritmo que leia dois valores digitados pelo usuário
//e calcule e mostre a multiplicação destes dois valores.
Var
   num1, num2, resultado: real

Inicio
   escreva("Digite o primeiro número da multiplicação:")
   leia(num1)
   
   escreva("Deigite o segundo número da multiplicação:")
   leia(num2)
   
   escreva("Resultado da multiplicação desses dois números são:")
   resultado <- num1 * num2
   escreva(resultado)


Fimalgoritmo